### ISSUE TITLE
nice tool!

### ISSUE THREAD

**Issue by aquynh** [furunkel/awasm#1]
this looks amazing! sounds like program synthesis to me.

linked to your tool just now from our website: http://www.capstone-engine.org/showcase.html

keep it up, cheers.

**Comment by furunkel** [comment]
Thanks!

In case you are interested, I have just finished the [Getting Started](https://github.com/furunkel/awasm/wiki/Getting-Started) wiki page.

**Comment by aquynh** [comment]
i havent looked at the source yet. can you give a quick explanation how this was done? do you need to translate machine code to IR?

**Comment by furunkel** [comment]
No. It contains a x64 runtime assembler and a "sandbox" JIT. The assembly is generated and executed on the fly. Then, fitness is determined by comparing written registers to the expected output.

**Comment by aquynh** [comment]
How do you generate assembly: randomly, or with  any strategy? What if you
have to combine more than 1 instruction to  get the desired result?

**Comment by furunkel** [comment]
Initially, the population is seeded randomly, yes. From then on it's a classical evolutionary process.
A program, usually, indeed is longer than a single instruction. I compiled an extensive [list](https://github.com/furunkel/awasm/blob/master/data/tables/x64.csv) of
instruction information that helps with compiling only valid sequences.

**Comment by aquynh** [comment]
this is interesting!

not sure what assembler you are using, but you might be interested in Keystone, a "sister" of Capstone: www.keystone-engine.org

**Comment by furunkel** [comment]
It contains its own assembler :).

**Comment by aquynh** [comment]
what is practical usage of Awasm?

**Comment by furunkel** [comment]
Good question. My goal is to have something that lies between a program synthesizer and a superoptimizer.
Awasm might implement simple programs (actually functions) in ways human would never think of.
Of course, classical superoptimizers will usually produce better code in terms of size or performance, but Awasm doesn't need an ordinary compiler to bootstrap the search process 
(generate the initial assembly).

So, on the long run, you might build something like a language compiler whose code generation is 
based on examples, or  a more complex program synthesizer, or a simple tool that helps with writing assembly by hand: it will propose a baseline program, that can be improved on manually.
