### ISSUE TITLE
Great software, any new version?

### ISSUE THREAD

**Issue by shgefu** [furunkel/awasm#2]
I want to know if any new version comes out? 

and I can not find any documents to tell me the detail information of how to use this engine.

**Comment by furunkel** [comment]
I'm working on a rewrite (that's using an interpreter for better performance), but I'm not sure it's gonna turn into anything.
I've fixed the broken links in the README; for your convenience:  [API documentation](https://evoasm.github.io/evoasm.rb/doc/), [examples](https://evoasm.github.io/evoasm.rb/doc/file.SymbolicRegression.html), [test cases](https://github.com/evoasm/evoasm.rb/tree/master/test/integration).
